package xprextravel.productos;

import javax.swing.JOptionPane;

public class VentanaRegistrar extends javax.swing.JFrame {

    private ManejarInventario miInventario;
    private VentanaProducto miProducto;
    private VentanaListaProductos miInventarioView;
    
    /**
     * Creates new form VentanaRegistrar
     */
    public VentanaRegistrar() {
        miInventario = new ManejarInventario();
        miProducto = new VentanaProducto();
        miInventarioView = new VentanaListaProductos();
        initComponents();
    }

    private void limpiar() {
        txtNombre.setText("");
        txtCodigo.setText("");
        txtCategoria.setText("");
        spinPrecio.setValue(0);
        spinCantidad.setValue(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        etiCodigo = new javax.swing.JLabel();
        eitNombre = new javax.swing.JLabel();
        EtiCategoria = new javax.swing.JLabel();
        etiPrecio = new javax.swing.JLabel();
        etiCantidad = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        spinCantidad = new javax.swing.JSpinner();
        spinPrecio = new javax.swing.JSpinner();
        btnRegistrar1 = new java.awt.Button();
        btnConsultar = new java.awt.Button();
        btnCategoria1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 214, 214));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 745, 46));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 745, 10));

        etiCodigo.setText("Código");
        getContentPane().add(etiCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 124, 68, -1));

        eitNombre.setText("Nombre");
        getContentPane().add(eitNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 166, 68, -1));

        EtiCategoria.setText("Categoría");
        getContentPane().add(EtiCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 200, 68, -1));

        etiPrecio.setText("Precio");
        getContentPane().add(etiPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 231, 68, -1));

        etiCantidad.setText("Cantidad");
        getContentPane().add(etiCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 268, 68, -1));
        getContentPane().add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 197, 132, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 163, 132, -1));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 121, 132, -1));
        getContentPane().add(spinCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 265, 132, -1));
        getContentPane().add(spinPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 231, 132, -1));

        btnRegistrar1.setBackground(new java.awt.Color(0, 204, 0));
        btnRegistrar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar1.setLabel("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 464, 164, 31));

        btnConsultar.setActionCommand("Consultar");
        btnConsultar.setLabel("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 121, -1, -1));

        btnCategoria1.setLabel("Listar productos");
        btnCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 505, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        try {
            
            System.out.println("VentanaRegistrar.btnRegistrar1ActionPerformed()");
            System.out.println("SpincantidadDef: "+spinCantidad.getValue());
            System.out.println("SpinPrecio1: "+spinPrecio.getValue());
            Producto prod = new Producto(txtNombre.getText(), txtCodigo.getText(), txtCategoria.getText(), (int) spinPrecio.getValue(), (int) spinCantidad.getValue());
            miInventario.agregarProducto(prod);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Uno de los valores ingresados es invalido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Producto prod = miInventario.consultarProducto(txtCodigo.getText());
        if (prod != null) {
            miProducto.cargarProducto(prod, miInventario);
            miProducto.setVisible(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria1ActionPerformed
        miInventarioView.cargar(miInventario);
        miInventarioView.setVisible(true);
    }//GEN-LAST:event_btnCategoria1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiCategoria;
    private java.awt.Button btnCategoria1;
    private java.awt.Button btnConsultar;
    private java.awt.Button btnRegistrar1;
    private javax.swing.JLabel eitNombre;
    private javax.swing.JLabel etiCantidad;
    private javax.swing.JLabel etiCodigo;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spinCantidad;
    private javax.swing.JSpinner spinPrecio;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
